package com.attence.employee.domain;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..department.id
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..department.name
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..department.parentId
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private String parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..department.mail1
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private String mail1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..department.mail2
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private String mail2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..department.phone1
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private String phone1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..department.phone2
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private String phone2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..department.content
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..department.id
     *
     * @return the value of test..department.id
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..department.id
     *
     * @param id the value for test..department.id
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..department.name
     *
     * @return the value of test..department.name
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..department.name
     *
     * @param name the value for test..department.name
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..department.parentId
     *
     * @return the value of test..department.parentId
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..department.parentId
     *
     * @param parentid the value for test..department.parentId
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..department.mail1
     *
     * @return the value of test..department.mail1
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public String getMail1() {
        return mail1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..department.mail1
     *
     * @param mail1 the value for test..department.mail1
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setMail1(String mail1) {
        this.mail1 = mail1 == null ? null : mail1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..department.mail2
     *
     * @return the value of test..department.mail2
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public String getMail2() {
        return mail2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..department.mail2
     *
     * @param mail2 the value for test..department.mail2
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setMail2(String mail2) {
        this.mail2 = mail2 == null ? null : mail2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..department.phone1
     *
     * @return the value of test..department.phone1
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public String getPhone1() {
        return phone1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..department.phone1
     *
     * @param phone1 the value for test..department.phone1
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setPhone1(String phone1) {
        this.phone1 = phone1 == null ? null : phone1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..department.phone2
     *
     * @return the value of test..department.phone2
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public String getPhone2() {
        return phone2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..department.phone2
     *
     * @param phone2 the value for test..department.phone2
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setPhone2(String phone2) {
        this.phone2 = phone2 == null ? null : phone2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..department.content
     *
     * @return the value of test..department.content
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..department.content
     *
     * @param content the value for test..department.content
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}