package com.attence.employee.domain;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..employee.id
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..employee.name
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..employee.birthday
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..employee.sex
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..employee.age
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private Byte age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..employee.mail1
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private String mail1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..employee.mail2
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private String mail2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..employee.phone1
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private String phone1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..employee.phone2
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private String phone2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..employee.postId
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private Integer postid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..employee.departmentId
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private Integer departmentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..employee.startDate
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private String startdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..employee.endDate
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private String enddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..employee.content
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..employee.id
     *
     * @return the value of test..employee.id
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..employee.id
     *
     * @param id the value for test..employee.id
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..employee.name
     *
     * @return the value of test..employee.name
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..employee.name
     *
     * @param name the value for test..employee.name
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..employee.birthday
     *
     * @return the value of test..employee.birthday
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..employee.birthday
     *
     * @param birthday the value for test..employee.birthday
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..employee.sex
     *
     * @return the value of test..employee.sex
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..employee.sex
     *
     * @param sex the value for test..employee.sex
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..employee.age
     *
     * @return the value of test..employee.age
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public Byte getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..employee.age
     *
     * @param age the value for test..employee.age
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setAge(Byte age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..employee.mail1
     *
     * @return the value of test..employee.mail1
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public String getMail1() {
        return mail1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..employee.mail1
     *
     * @param mail1 the value for test..employee.mail1
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setMail1(String mail1) {
        this.mail1 = mail1 == null ? null : mail1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..employee.mail2
     *
     * @return the value of test..employee.mail2
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public String getMail2() {
        return mail2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..employee.mail2
     *
     * @param mail2 the value for test..employee.mail2
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setMail2(String mail2) {
        this.mail2 = mail2 == null ? null : mail2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..employee.phone1
     *
     * @return the value of test..employee.phone1
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public String getPhone1() {
        return phone1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..employee.phone1
     *
     * @param phone1 the value for test..employee.phone1
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setPhone1(String phone1) {
        this.phone1 = phone1 == null ? null : phone1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..employee.phone2
     *
     * @return the value of test..employee.phone2
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public String getPhone2() {
        return phone2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..employee.phone2
     *
     * @param phone2 the value for test..employee.phone2
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setPhone2(String phone2) {
        this.phone2 = phone2 == null ? null : phone2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..employee.postId
     *
     * @return the value of test..employee.postId
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public Integer getPostid() {
        return postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..employee.postId
     *
     * @param postid the value for test..employee.postId
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setPostid(Integer postid) {
        this.postid = postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..employee.departmentId
     *
     * @return the value of test..employee.departmentId
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public Integer getDepartmentid() {
        return departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..employee.departmentId
     *
     * @param departmentid the value for test..employee.departmentId
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setDepartmentid(Integer departmentid) {
        this.departmentid = departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..employee.startDate
     *
     * @return the value of test..employee.startDate
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public String getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..employee.startDate
     *
     * @param startdate the value for test..employee.startDate
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setStartdate(String startdate) {
        this.startdate = startdate == null ? null : startdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..employee.endDate
     *
     * @return the value of test..employee.endDate
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public String getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..employee.endDate
     *
     * @param enddate the value for test..employee.endDate
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setEnddate(String enddate) {
        this.enddate = enddate == null ? null : enddate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..employee.content
     *
     * @return the value of test..employee.content
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..employee.content
     *
     * @param content the value for test..employee.content
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}