package com.attence.employee.domain;

public class Menu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..menu.id
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..menu.path
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..menu.name
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..menu.component
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private String component;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..menu.showInNavi
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private Boolean showinnavi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..menu.parentId
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private Integer parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..menu.enable
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private Boolean enable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..menu.id
     *
     * @return the value of test..menu.id
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..menu.id
     *
     * @param id the value for test..menu.id
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..menu.path
     *
     * @return the value of test..menu.path
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..menu.path
     *
     * @param path the value for test..menu.path
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..menu.name
     *
     * @return the value of test..menu.name
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..menu.name
     *
     * @param name the value for test..menu.name
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..menu.component
     *
     * @return the value of test..menu.component
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public String getComponent() {
        return component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..menu.component
     *
     * @param component the value for test..menu.component
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setComponent(String component) {
        this.component = component == null ? null : component.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..menu.showInNavi
     *
     * @return the value of test..menu.showInNavi
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public Boolean getShowinnavi() {
        return showinnavi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..menu.showInNavi
     *
     * @param showinnavi the value for test..menu.showInNavi
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setShowinnavi(Boolean showinnavi) {
        this.showinnavi = showinnavi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..menu.parentId
     *
     * @return the value of test..menu.parentId
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..menu.parentId
     *
     * @param parentid the value for test..menu.parentId
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..menu.enable
     *
     * @return the value of test..menu.enable
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..menu.enable
     *
     * @param enable the value for test..menu.enable
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }
}