package com.attence.employee.domain;

public class MenuToRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..menuToRole.id
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..menuToRole.menuId
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private Integer menuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..menuToRole.roleId
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private Integer roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..menuToRole.id
     *
     * @return the value of test..menuToRole.id
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..menuToRole.id
     *
     * @param id the value for test..menuToRole.id
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..menuToRole.menuId
     *
     * @return the value of test..menuToRole.menuId
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public Integer getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..menuToRole.menuId
     *
     * @param menuid the value for test..menuToRole.menuId
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..menuToRole.roleId
     *
     * @return the value of test..menuToRole.roleId
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..menuToRole.roleId
     *
     * @param roleid the value for test..menuToRole.roleId
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }
}