package com.attence.employee.domain;

public class Post {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..post.id
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..post.name
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..post.id
     *
     * @return the value of test..post.id
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..post.id
     *
     * @param id the value for test..post.id
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..post.name
     *
     * @return the value of test..post.name
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..post.name
     *
     * @param name the value for test..post.name
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}