package com.attence.employee.domain;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..user.id
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..user.username
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..user.password
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..user.enable
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    private Boolean enable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..user.id
     *
     * @return the value of test..user.id
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..user.id
     *
     * @param id the value for test..user.id
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..user.username
     *
     * @return the value of test..user.username
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..user.username
     *
     * @param username the value for test..user.username
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..user.password
     *
     * @return the value of test..user.password
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..user.password
     *
     * @param password the value for test..user.password
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..user.enable
     *
     * @return the value of test..user.enable
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..user.enable
     *
     * @param enable the value for test..user.enable
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }
}