package com.attence.employee.dao;

import com.attence.employee.domain.Department;
import com.attence.employee.domain.DepartmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..department
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    int deleteByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..department
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..department
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    int insert(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..department
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    int insertSelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..department
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    List<Department> selectByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..department
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    Department selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..department
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    int updateByExampleSelective(@Param("record") Department record, @Param("example") DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..department
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    int updateByExample(@Param("record") Department record, @Param("example") DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..department
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    int updateByPrimaryKeySelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..department
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    int updateByPrimaryKey(Department record);
}