package com.attence.employee.dao;

import com.attence.employee.domain.Employee;
import com.attence.employee.domain.EmployeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..employee
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    int deleteByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..employee
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..employee
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..employee
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    int insertSelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..employee
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    List<Employee> selectByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..employee
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    Employee selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..employee
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    int updateByExampleSelective(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..employee
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    int updateByExample(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..employee
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    int updateByPrimaryKeySelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..employee
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    int updateByPrimaryKey(Employee record);
}