package com.attence.employee.dao;

import com.attence.employee.domain.UserToRole;
import com.attence.employee.domain.UserToRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserToRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..userToRole
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    int deleteByExample(UserToRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..userToRole
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..userToRole
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    int insert(UserToRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..userToRole
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    int insertSelective(UserToRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..userToRole
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    List<UserToRole> selectByExample(UserToRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..userToRole
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    UserToRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..userToRole
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserToRole record, @Param("example") UserToRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..userToRole
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    int updateByExample(@Param("record") UserToRole record, @Param("example") UserToRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..userToRole
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    int updateByPrimaryKeySelective(UserToRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..userToRole
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    int updateByPrimaryKey(UserToRole record);
}