package com.attence.employee.dao;

import com.attence.employee.domain.User;
import com.attence.employee.domain.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..user
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..user
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..user
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..user
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..user
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..user
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..user
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..user
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..user
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..user
     *
     * @mbg.generated Thu Dec 24 15:07:01 CST 2020
     */
    int updateByPrimaryKey(User record);
}